### ISSUE TITLE
Update the scripts to the latest version of libvirt

### ISSUE THREAD

**Issue by ycollet** [photron/msys_setup#4]
A while ago, libvirt-0.9.11 has been released. 
It would be a good idea to update the scripts to this latest version (version 0.9.3 doesn't support virtualbox-4.1.*).

YC

**Comment by photron** [comment]
Yes, I didn't spent any time on this scripts lately and didn't keep up with recent libvirt releases.

I just pushed updated scripts for libvirt 0.9.4, 0.9.10 and 0.9.11.
