### ISSUE TITLE
libxml2mod dll not built for libxml2 2.9.0

### ISSUE THREAD

**Issue by simonvanderveldt** [photron/msys_setup#5]
When running the latest compile_libxml2.sh it fails at copying libxml2mod.dll. It seems because libxml2mod.dll isn't built.

When running the older version of compile_libxml2.sh for libxml2 2.7.8 everything works as expected, libxml2mod.dll is built and it is copied as it should.

**Comment by photron** [comment]
Fixed by commit 18ac64649890c115260c3da1957f59db0496b5d2
